TEAMS = {
    "AFC Bournemouth" : "AFC Bournemouth",
    "Arsenal FC" : "Arsenal FC",
    "Aston Villa" : "Aston Villa FC",
    "Brentford FC" : "Brentford FC",
    "Brighton & Hove Albion" : "Brighton & Hove Albion FC",
    "Burnley FC" : "Burnley FC",
    "Chelsea FC" : "Chelsea FC",
    "Crystal Palace" : "Crystal Palace FC",
    "Everton FC" : "Everton FC",
    "Fulham FC" : "Fulham FC",
    "Leeds United" : "Leeds United FC",
    "Leicester City" : "Leicester City FC",
    "Liverpool FC" : "Liverpool FC",
    "Luton Town": "Luton Town FC",
    "Manchester City" : "Manchester City FC",
    "Manchester United" : "Manchester United FC",
    "Newcastle United" : "Newcastle United FC",
    "Nottingham Forest" : "Nottingham Forest FC",
    "Southampton FC" : "Southampton FC",
    "Sheffield United": "Sheffield United FC",
    "Tottenham Hotspur" : "Tottenham Hotspur FC",
    "West Ham United" : "West Ham United FC",
    "Wolverhampton Wanderers" : "Wolverhampton Wanderers FC"
}

TEAMSFIXTURES = {
    'Arsenal':  "Arsenal FC",
    'Aston Villa' : "Aston Villa FC",
    'Bournemouth': "AFC Bournemouth" ,
    'Brentford': "Brentford FC",
    'Brighton': "Brighton & Hove Albion FC",
    'Burnley': "Burnley FC",
    'Chelsea': "Chelsea FC",
    'Crystal Palace': "Crystal Palace FC",
    'Everton': "Everton FC",
    'Fulham': "Fulham FC",
    'Leeds': "Leeds United FC",
    'Leicester': "Leicester City FC",
    'Liverpool': "Liverpool FC",
    'Luton': "Luton Town FC",
    'Man City': "Manchester City FC",
    'Man Utd': "Manchester United FC",
    'Newcastle': "Newcastle United FC",
    'Nottingham Forest': "Nottingham Forest FC",
    'Southampton': "Southampton FC",
    'Sheffield Utd': "Sheffield United FC",
    'Spurs': "Tottenham Hotspur FC",
    'West Ham': "West Ham United FC",
    'Wolves':  "Wolverhampton Wanderers FC"
}