# Generated by Django 4.2.8 on 2024-01-11 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("premier_league_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Players",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(blank=True, max_length=50)),
                ("age", models.IntegerField()),
                ("nationality", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=20)),
                ("minutes_played", models.IntegerField()),
                ("yellow_cards", models.IntegerField()),
                ("red_cards", models.IntegerField()),
                ("goals", models.IntegerField()),
                ("assists", models.IntegerField()),
                ("clean_sheets", models.IntegerField()),
                ("total_apps", models.IntegerField()),
                ("game_starts", models.IntegerField()),
                ("sub_apps", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="premier_league_api.teams",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("first_name", "last_name", "nationality", "team_name")
                },
            },
        ),
    ]
