# Generated by Django 4.2.8 on 2023-12-19 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("premier_league_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fixtures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_week", models.IntegerField()),
                ("date_time", models.DateTimeField()),
                ("stadium", models.CharField(max_length=50)),
                ("home_score", models.IntegerField(null=True)),
                ("away_score", models.IntegerField(null=True)),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_team",
                        to="premier_league_api.teams",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_team",
                        to="premier_league_api.teams",
                    ),
                ),
            ],
            options={"unique_together": {("game_week", "home_team", "away_team")},},
        ),
    ]
