# Generated by Django 4.2.8 on 2023-12-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("premier_league_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="managers", old_name="team", new_name="team_name",
        ),
        migrations.RenameField(
            model_name="teams", old_name="name", new_name="team_name",
        ),
    ]
