# Generated by Django 4.2.8 on 2023-12-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("premier_league_api", "0002_rename_team_managers_team_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="teams", name="id",),
        migrations.AlterField(
            model_name="teams",
            name="team_name",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
