# Generated by Django 4.2.8 on 2023-12-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("premier_league_api", "0004_teams_id_alter_teams_team_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teams", old_name="team_name", new_name="name",
        ),
    ]
