# Generated by Django 4.2.8 on 2023-12-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("premier_league_api", "0005_rename_team_name_teams_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teams",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
