# Generated by Django 4.2.8 on 2023-12-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("premier_league_api", "0006_alter_teams_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teams",
            name="name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
