# Generated by Django 4.2.8 on 2023-12-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("premier_league_api", "0007_alter_teams_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="managers",
            name="contract_expiry",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="managers",
            name="updated_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
